### ISSUE TITLE
Add .travis.yml

### ISSUE THREAD

**Issue by jsbean** [dn-m/Helper#1]

**Comment by jsbean** [comment]
Use this as template:

```YAML
language: objective-c
osx_image: xcode8
env:
  matrix:
    - DESTINATION="platform=iOS Simulator,OS=9.3,name=iPad 2" 
      SCHEME="ArithmeticTools"
    - DESTINATION="platform=iOS Simulator,OS=10.0,name=iPad Pro (12.9 inch)"
      SCHEME="ArithmeticTools"
    - DESTINATION="platform=OS X" 
      SCHEME="ArithmeticToolsMac"

before_script: carthage update

script: travis_retry xcodebuild test 
  -project ArithmeticTools.xcodeproj
  -scheme "${SCHEME}"
  -destination "${DESTINATION}"
  TOOLCHAINS=swift

after_success:
  - bash <(curl -s https://codecov.io/bash)
```
